[package]
name = "pz-13p-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "1", features = [] }
walkdir = "2"
winreg = "0.52"
regex = "1"
which = "6"
